spring:
  application:
    name: twinkli-service

server:
  address: 0.0.0.0
  port: 8080

api:
  service:
    frontend: ${TWINKLI_FRONTEND:http://localhost:4200,https://6w50slcv-4200.euw.devtunnels.ms}

telegram:
  bot:
    token: ${BOT_TOKEN:test_token}